#!/usr/bin/env python3
from __future__ import annotations

import importlib.machinery
import importlib.util
import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load(name: str, path: Path):
    loader = importlib.machinery.SourceFileLoader(name, str(path))
    spec = importlib.util.spec_from_loader(name, loader)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    loader.exec_module(module)
    return module


collector = load("adguard_resolver_phase2_preflight", ROOT / "ops/bin/adguard-resolver-phase2-preflight")
verifier = load("adguard_resolver_phase2_preflight_verify", ROOT / "ops/bin/adguard-resolver-phase2-preflight-verify")


class AdGuardResolverPhase2Tests(unittest.TestCase):
    def ready_payload(self):
        return {
            "schema": collector.SCHEMA,
            "status": "PASS",
            "mutation_started": False,
            "authorization_consumed": False,
            "privacy": {
                "raw_network_addresses_emitted": False,
                "connection_identity_emitted": False,
                "raw_networkmanager_profile_read": False,
                "credentials_read": False,
            },
            "networkmanager": {
                "version": "nmcli tool, version 1.42.4",
                "default_route_device_fingerprint": "0123456789abcdef",
                "active_profile_fingerprint": "fedcba9876543210",
                "profile": {
                    "ipv4_method": "manual",
                    "ipv4_dns_classes": ["ipv4_public", "loopback"],
                    "ipv4_dns_count": 2,
                    "ipv4_ignore_auto_dns": True,
                    "ipv6_method": "auto",
                    "ipv6_dns_classes": [],
                    "ipv6_dns_count": 0,
                    "ipv6_ignore_auto_dns": False,
                },
                "runtime_dns_classes": ["ipv4_public", "ipv6_link_local", "loopback"],
                "runtime_dns_count": 3,
            },
            "resolv_conf": {
                "owner_class": "networkmanager_generated",
                "nameserver_classes": ["ipv4_public", "ipv6_link_local", "loopback"],
                "nameserver_count": 3,
                "rotate_present": False,
            },
            "systemd_resolved_active": False,
            "dns_listeners": {"tcp_53": True, "udp_53": True},
            "ordinary_dns": {"system_resolver_answered": True, "adguard_loopback_answered": True},
        }

    def test_profile_parser_reduces_dns_to_classes(self):
        raw = (
            "ipv4.method:manual\n"
            "ipv4.dns:127.0.0.1,1.1.1.1\n"
            "ipv4.ignore-auto-dns:yes\n"
            "ipv6.method:auto\n"
            "ipv6.dns:\n"
            "ipv6.ignore-auto-dns:no\n"
        )
        profile = collector.parse_profile(raw, "192.0.2.1")
        self.assertEqual(profile["ipv4_dns_classes"], ["ipv4_public", "loopback"])
        self.assertEqual(profile["ipv4_dns_count"], 2)
        self.assertEqual(profile["ipv6_dns_classes"], [])
        self.assertFalse(profile["ipv6_ignore_auto_dns"])

    def test_profile_parser_fails_closed_on_unexpected_shape(self):
        with self.assertRaisesRegex(collector.PreflightError, "profile_output_incomplete"):
            collector.parse_profile("ipv4.method:manual\n", "192.0.2.1")
        with self.assertRaisesRegex(collector.PreflightError, "profile_dns_address_invalid"):
            collector.parse_dns_list("127.0.0.1,not-an-ip", 4, "192.0.2.1")

    def test_resolv_conf_reduction_and_rotate_detection(self):
        parsed = collector.parse_resolv_conf(
            "# Generated by NetworkManager\n"
            "nameserver 127.0.0.1\n"
            "nameserver 1.1.1.1\n"
            "nameserver fe80::1\n",
            "/run/NetworkManager/resolv.conf",
            "192.0.2.1",
        )
        self.assertEqual(parsed["nameserver_classes"], ["ipv4_public", "ipv6_link_local", "loopback"])
        self.assertEqual(parsed["nameserver_count"], 3)
        self.assertFalse(parsed["rotate_present"])
        rotated = collector.parse_resolv_conf(
            "nameserver 127.0.0.1\noptions timeout:2 rotate\n",
            "/run/NetworkManager/resolv.conf",
            "192.0.2.1",
        )
        self.assertTrue(rotated["rotate_present"])

    def test_ready_payload_verifies(self):
        result = verifier.verify(self.ready_payload())
        self.assertEqual(result["status"], "READY_PHASE2")
        self.assertTrue(result["profile_public_ipv4_fallback_confirmed"])
        self.assertTrue(result["ipv6_auto_dns_fallback_confirmed"])
        self.assertFalse(result["mutation_started"])
        self.assertFalse(result["authorization_consumed"])

    def test_verifier_fails_closed_on_shape_drift(self):
        payload = self.ready_payload()
        payload["networkmanager"]["profile"]["ipv4_dns_classes"] = ["loopback"]
        with self.assertRaisesRegex(verifier.VerifyError, "ipv4_profile_dns_shape_unexpected"):
            verifier.verify(payload)
        payload = self.ready_payload()
        payload["resolv_conf"]["rotate_present"] = True
        with self.assertRaisesRegex(verifier.VerifyError, "resolv_conf_rotate_unexpected"):
            verifier.verify(payload)

    def test_phase2_contract_is_source_disabled_and_narrow(self):
        contract = json.loads((ROOT / "ops/contracts/adguard-host-resolver-phase2-v1.json").read_text(encoding="utf-8"))
        self.assertTrue(contract["source_only"])
        self.assertFalse(contract["execution_enabled"])
        mutation = contract["mutation"]
        self.assertEqual(mutation["max_forward_writes"], 2)
        profile_write = mutation["persistent_profile_write"]
        self.assertEqual(profile_write["allowed_properties"], ["ipv4.dns", "ipv6.ignore-auto-dns"])
        self.assertEqual(profile_write["required_exact_values"]["ipv4.dns"], ["127.0.0.1"])
        self.assertTrue(profile_write["required_exact_values"]["ipv6.ignore-auto-dns"])
        self.assertFalse(mutation["runtime_reapply_write"]["connection_down_up_allowed"])
        self.assertFalse(mutation["runtime_reapply_write"]["networkmanager_restart_allowed"])
        self.assertFalse(mutation["resolv_conf_direct_write_allowed"])
        self.assertFalse(contract["failure"]["automatic_retry"])
        self.assertFalse(contract["failure"]["automatic_rollback"])

    def test_collect_emits_no_raw_addresses_or_connection_identity(self):
        profile_uuid = "123e4567-e89b-12d3-a456-426614174000"

        def fake(command):
            cmd = tuple(command)
            if cmd == ("ip", "-4", "route", "show", "default"):
                return collector.CommandResult(0, "default via 192.0.2.1 dev eth0 metric 100\n")
            if cmd == ("nmcli", "--version"):
                return collector.CommandResult(0, "nmcli tool, version 1.42.4\n")
            if cmd == ("nmcli", "-g", "GENERAL.CON-UUID", "device", "show", "eth0"):
                return collector.CommandResult(0, profile_uuid + "\n")
            if cmd[:3] == ("nmcli", "-m", "multiline") and "connection" in cmd:
                return collector.CommandResult(0,
                    "ipv4.method:manual\nipv4.dns:127.0.0.1,1.1.1.1\nipv4.ignore-auto-dns:yes\n"
                    "ipv6.method:auto\nipv6.dns:\nipv6.ignore-auto-dns:no\n")
            if cmd[:3] == ("nmcli", "-m", "multiline") and "device" in cmd:
                return collector.CommandResult(0,
                    "IP4.DNS[1]:127.0.0.1\nIP4.DNS[2]:1.1.1.1\nIP6.DNS[1]:fe80::1\n")
            if cmd == ("systemctl", "is-active", "systemd-resolved"):
                return collector.CommandResult(3, "inactive\n")
            if cmd == ("ss", "-H", "-lntu"):
                return collector.CommandResult(0, "udp UNCONN 0 0 *:53 *:*\ntcp LISTEN 0 4096 *:53 *:*\n")
            if cmd[0] == "dig":
                return collector.CommandResult(0, "203.0.113.10\n")
            raise AssertionError(cmd)

        payload = collector.collect(fake, lambda: (
            "# Generated by NetworkManager\nnameserver 127.0.0.1\nnameserver 1.1.1.1\nnameserver fe80::1\n",
            "/run/NetworkManager/resolv.conf",
        ))
        rendered = json.dumps(payload, sort_keys=True)
        for value in ("192.0.2.1", "1.1.1.1", "fe80::1", "eth0", profile_uuid):
            self.assertNotIn(value, rendered)
        self.assertEqual(verifier.verify(payload)["status"], "READY_PHASE2")


if __name__ == "__main__":
    unittest.main()
